site_name: phpMyFAQ v4.2
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
nav:
  - 1. Introduction: '1-index.md'
  - 2. Installation: '2-installation.md'
  - 3. Production Deployment: '3-deployment.md'
  - 4. Docker Cheat Sheet: '4-docker-cheatsheet.md'
  - 5. Updating phpMyFAQ: '5-update.md'
  - 6. Use phpMyFAQ: '6-usage.md'
  - 7. Manage phpMyFAQ: '7-administration.md'
    8. phpMyFAQ configuration reference: '8-configuration.md'
  - 9. AI-Assisted Translation feature: '8-ai-translation.md'
  - 10. Developer documentation: '9-development.md'
  - 11. Plugins: '10-plugins.md'
  - 12. MCP Server: '11-mcp-server.md'
  - 13. Thank you!: '12-thank-you.md'
