/**
 * Custom Pages administration
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at https://mozilla.org/MPL/2.0/.
 *
 * @package   phpMyFAQ
 * @author    Thorsten Rinne <thorsten@phpmyfaq.de>
 * @copyright 2026 phpMyFAQ Team
 * @license   https://www.mozilla.org/MPL/2.0/ Mozilla Public License Version 2.0
 * @link      https://www.phpmyfaq.de
 * @since     2026-01-15
 */

import { activatePage, addPage, checkSlug, deletePage, updatePage } from '../api';
import { Modal } from 'bootstrap';
import { pushErrorNotification, pushNotification } from '../../../../assets/src/utils';
import { Response } from '../interfaces';
import { renderPageEditor } from './editor';

interface PageData {
  pageTitle: string;
  slug: string;
  content: string;
  authorName: string;
  authorEmail: string;
  active: boolean;
  lang: string;
  csrfToken: string;
  id?: string;
  [key: string]: unknown;
}

/**
 * Generates a URL-friendly slug from a title
 */
const generateSlug = (title: string): string => {
  return title
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');
};

/**
 * Debounce function for slug validation
 */
const debounce = <T extends (...args: unknown[]) => void>(
  func: T,
  wait: number
): ((...args: Parameters<T>) => void) => {
  let timeout: ReturnType<typeof setTimeout>;
  return (...args: Parameters<T>): void => {
    clearTimeout(timeout);
    timeout = setTimeout(() => func(...args), wait);
  };
};

/**
 * Updates character counter for SEO fields
 */
const updateCharCounter = (inputId: string, counterId: string, maxLength: number): void => {
  const input = document.getElementById(inputId) as HTMLInputElement | HTMLTextAreaElement | null;
  const counter = document.getElementById(counterId) as HTMLElement | null;

  if (input && counter) {
    const updateCount = () => {
      const length = input.value.length;
      counter.textContent = length.toString();

      if (length > maxLength) {
        counter.classList.add('text-danger');
        counter.classList.remove('text-warning');
      } else if (length > maxLength * 0.9) {
        counter.classList.add('text-warning');
        counter.classList.remove('text-danger');
      } else {
        counter.classList.remove('text-danger', 'text-warning');
      }
    };

    input.addEventListener('input', updateCount);
    updateCount();
  }
};

/**
 * Validates slug availability
 */
const validateSlug = async (slug: string, lang: string, csrfToken: string, excludeId?: string): Promise<boolean> => {
  const response = (await checkSlug(slug, lang, csrfToken, excludeId)) as { available: boolean };
  return response.available;
};

/**
 * Handle add page form
 */
export const handleAddPage = (): void => {
  const form = document.getElementById('pmf-add-page-form') as HTMLFormElement | null;
  if (!form) return;

  // Initialize WYSIWYG editor for content field
  renderPageEditor();

  const titleInput = document.getElementById('pageTitle') as HTMLInputElement | null;
  const slugInput = document.getElementById('slug') as HTMLInputElement | null;
  const csrfToken = (document.getElementById('pmf-csrf-token') as HTMLInputElement)?.value;
  const langInput = document.getElementById('lang') as HTMLSelectElement | null;

  // Auto-generate slug from title
  if (titleInput && slugInput) {
    titleInput.addEventListener('input', () => {
      if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
        slugInput.value = generateSlug(titleInput.value);
        slugInput.dataset.autoGenerated = 'true';
      }
    });

    slugInput.addEventListener('input', () => {
      slugInput.dataset.autoGenerated = 'false';
    });
  }

  // Real-time slug validation
  if (slugInput && langInput) {
    const validateSlugDebounced = debounce(async () => {
      const slug = slugInput.value;
      const lang = langInput.value;
      const feedback = document.getElementById('slug-feedback') as HTMLElement | null;

      if (!slug || !lang) return;

      const isAvailable = await validateSlug(slug, lang, csrfToken);

      if (isAvailable) {
        slugInput.classList.remove('is-invalid');
        slugInput.classList.add('is-valid');
        if (feedback) feedback.textContent = '';
      } else {
        slugInput.classList.remove('is-valid');
        slugInput.classList.add('is-invalid');
        if (feedback) feedback.textContent = 'This slug already exists for this language';
      }
    }, 500);

    slugInput.addEventListener('input', validateSlugDebounced);
    langInput.addEventListener('change', validateSlugDebounced);
  }

  // SEO character counters
  updateCharCounter('seoTitle', 'seo-title-counter', 60);
  updateCharCounter('seoDescription', 'seo-description-counter', 160);

  // Form submission
  const submitButton = document.getElementById('pmf-submit-page') as HTMLButtonElement | null;
  if (submitButton) {
    submitButton.addEventListener('click', async (event: Event) => {
      event.preventDefault();

      const data: PageData = {
        pageTitle: (document.getElementById('pageTitle') as HTMLInputElement).value,
        slug: (document.getElementById('slug') as HTMLInputElement).value,
        content: (document.getElementById('content') as HTMLTextAreaElement).value,
        authorName: (document.getElementById('authorName') as HTMLInputElement).value,
        authorEmail: (document.getElementById('authorEmail') as HTMLInputElement).value,
        active: (document.getElementById('active') as HTMLInputElement).checked,
        lang: (document.getElementById('lang') as HTMLSelectElement).value,
        seoTitle: (document.getElementById('seoTitle') as HTMLInputElement).value,
        seoDescription: (document.getElementById('seoDescription') as HTMLTextAreaElement).value,
        seoRobots: (document.getElementById('seoRobots') as HTMLSelectElement).value,
        csrfToken: csrfToken,
      };

      const response = (await addPage(data)) as unknown as Response;
      if (typeof response.success === 'string') {
        pushNotification(response.success);
        setTimeout(() => {
          window.location.href = './pages';
        }, 2000);
      } else {
        pushErrorNotification(response.error || 'An error occurred');
      }
    });
  }
};

/**
 * Handle translate page form
 */
export const handleTranslatePage = (): void => {
  const form = document.getElementById('pmf-translate-page-form') as HTMLFormElement | null;
  if (!form) return;

  // Initialize WYSIWYG editor for content field
  renderPageEditor();

  const titleInput = document.getElementById('pageTitle') as HTMLInputElement | null;
  const slugInput = document.getElementById('slug') as HTMLInputElement | null;
  const csrfToken = (document.getElementById('pmf-csrf-token') as HTMLInputElement)?.value;
  const langInput = document.getElementById('lang') as HTMLSelectElement | null;
  const pageIdInput = document.getElementById('pageId') as HTMLInputElement | null;

  // Auto-generate slug from title
  if (titleInput && slugInput) {
    titleInput.addEventListener('input', () => {
      if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
        slugInput.value = generateSlug(titleInput.value);
        slugInput.dataset.autoGenerated = 'true';
      }
    });

    slugInput.addEventListener('input', () => {
      slugInput.dataset.autoGenerated = 'false';
    });
  }

  // Real-time slug validation
  if (slugInput && langInput) {
    const validateSlugDebounced = debounce(async () => {
      const slug = slugInput.value;
      const lang = langInput.value;
      const feedback = document.getElementById('slug-feedback') as HTMLElement | null;

      if (!slug || !lang) return;

      const isAvailable = await validateSlug(slug, lang, csrfToken);

      if (isAvailable) {
        slugInput.classList.remove('is-invalid');
        slugInput.classList.add('is-valid');
        if (feedback) feedback.textContent = '';
      } else {
        slugInput.classList.remove('is-valid');
        slugInput.classList.add('is-invalid');
        if (feedback) feedback.textContent = 'This slug already exists for this language';
      }
    }, 500);

    slugInput.addEventListener('input', validateSlugDebounced);
    langInput.addEventListener('change', validateSlugDebounced);
  }

  // SEO character counters
  updateCharCounter('seoTitle', 'seo-title-counter', 60);
  updateCharCounter('seoDescription', 'seo-description-counter', 160);

  // Form submission
  const submitButton = document.getElementById('pmf-submit-page') as HTMLButtonElement | null;
  if (submitButton) {
    submitButton.addEventListener('click', async (event: Event) => {
      event.preventDefault();

      const data: PageData = {
        pageId: pageIdInput?.value, // Include pageId for translation
        pageTitle: (document.getElementById('pageTitle') as HTMLInputElement).value,
        slug: (document.getElementById('slug') as HTMLInputElement).value,
        content: (document.getElementById('content') as HTMLTextAreaElement).value,
        authorName: (document.getElementById('authorName') as HTMLInputElement).value,
        authorEmail: (document.getElementById('authorEmail') as HTMLInputElement).value,
        active: (document.getElementById('active') as HTMLInputElement).checked,
        lang: (document.getElementById('lang') as HTMLSelectElement).value,
        seoTitle: (document.getElementById('seoTitle') as HTMLInputElement).value,
        seoDescription: (document.getElementById('seoDescription') as HTMLTextAreaElement).value,
        seoRobots: (document.getElementById('seoRobots') as HTMLSelectElement).value,
        csrfToken: csrfToken,
      };

      const response = (await addPage(data)) as unknown as Response;
      if (typeof response.success === 'string') {
        pushNotification(response.success);
        setTimeout(() => {
          window.location.href = './pages';
        }, 2000);
      } else {
        pushErrorNotification(response.error || 'An error occurred');
      }
    });
  }
};

/**
 * Handle edit page form
 */
export const handleEditPage = (): void => {
  const form = document.getElementById('pmf-edit-page-form') as HTMLFormElement | null;
  if (!form) return;

  // Initialize WYSIWYG editor for content field
  renderPageEditor();

  const slugInput = document.getElementById('slug') as HTMLInputElement | null;
  const csrfToken = (document.getElementById('pmf-csrf-token') as HTMLInputElement)?.value;
  const langInput = document.getElementById('lang') as HTMLInputElement | null;
  const pageIdInput = document.getElementById('pageId') as HTMLInputElement | null;

  // Real-time slug validation (excluding current page)
  if (slugInput && langInput && pageIdInput) {
    const validateSlugDebounced = debounce(async () => {
      const slug = slugInput.value;
      const lang = langInput.value;
      const pageId = pageIdInput.value;
      const feedback = document.getElementById('slug-feedback') as HTMLElement | null;

      if (!slug || !lang) return;

      const isAvailable = await validateSlug(slug, lang, csrfToken, pageId);

      if (isAvailable) {
        slugInput.classList.remove('is-invalid');
        slugInput.classList.add('is-valid');
        if (feedback) feedback.textContent = '';
      } else {
        slugInput.classList.remove('is-valid');
        slugInput.classList.add('is-invalid');
        if (feedback) feedback.textContent = 'This slug already exists for this language';
      }
    }, 500);

    slugInput.addEventListener('input', validateSlugDebounced);
  }

  // SEO character counters
  updateCharCounter('seoTitle', 'seo-title-counter', 60);
  updateCharCounter('seoDescription', 'seo-description-counter', 160);

  // Form submission
  const submitButton = document.getElementById('pmf-submit-page') as HTMLButtonElement | null;
  if (submitButton) {
    submitButton.addEventListener('click', async (event: Event) => {
      event.preventDefault();

      const data: PageData = {
        id: (document.getElementById('pageId') as HTMLInputElement).value,
        pageTitle: (document.getElementById('pageTitle') as HTMLInputElement).value,
        slug: (document.getElementById('slug') as HTMLInputElement).value,
        content: (document.getElementById('content') as HTMLTextAreaElement).value,
        authorName: (document.getElementById('authorName') as HTMLInputElement).value,
        authorEmail: (document.getElementById('authorEmail') as HTMLInputElement).value,
        active: (document.getElementById('active') as HTMLInputElement).checked,
        lang: (document.getElementById('lang') as HTMLInputElement).value,
        seoTitle: (document.getElementById('seoTitle') as HTMLInputElement).value,
        seoDescription: (document.getElementById('seoDescription') as HTMLTextAreaElement).value,
        seoRobots: (document.getElementById('seoRobots') as HTMLSelectElement).value,
        csrfToken: csrfToken,
      };

      const response = (await updatePage(data)) as unknown as Response;
      if (typeof response.success === 'string') {
        pushNotification(response.success);
        setTimeout(() => {
          window.location.href = './pages';
        }, 2000);
      } else {
        pushErrorNotification(response.error || 'An error occurred');
      }
    });
  }
};

/**
 * Handle pages list (delete and activate)
 */
export const handlePages = (): void => {
  // Delete page functionality
  const deleteButtons = document.querySelectorAll<HTMLButtonElement>('#deletePage');
  if (deleteButtons.length > 0) {
    deleteButtons.forEach((button) => {
      button.addEventListener('click', (event: Event) => {
        event.preventDefault();
        const modal = new Modal(document.getElementById('confirmDeletePageModal') as HTMLElement);
        const pageId = button.getAttribute('data-pmf-pageid') as string;
        const pageLang = button.getAttribute('data-pmf-lang') as string;

        (document.getElementById('pageId') as HTMLInputElement).value = pageId;
        (document.getElementById('pageLang') as HTMLInputElement).value = pageLang;
        modal.show();
      });
    });

    const deleteAction = document.getElementById('pmf-delete-page-action') as HTMLButtonElement | null;
    if (deleteAction) {
      deleteAction.addEventListener('click', async (event: Event) => {
        event.preventDefault();
        const csrfToken = (document.getElementById('pmf-csrf-token-delete') as HTMLInputElement).value;
        const pageId = (document.getElementById('pageId') as HTMLInputElement).value;
        const pageLang = (document.getElementById('pageLang') as HTMLInputElement).value;

        const response = (await deletePage(csrfToken, pageId, pageLang)) as unknown as Response;
        if (typeof response.success === 'string') {
          pushNotification(response.success);
          setTimeout(() => {
            window.location.reload();
          }, 2000);
        } else {
          pushErrorNotification(response.error || 'An error occurred');
        }
      });
    }
  }

  // Activate/deactivate functionality
  const activateCheckboxes = document.querySelectorAll<HTMLInputElement>('#activate');
  activateCheckboxes.forEach((checkbox) => {
    checkbox.addEventListener('click', async () => {
      const pageId = checkbox.getAttribute('data-pmf-id') as string;
      const csrfToken = checkbox.getAttribute('data-pmf-csrf-token') as string;
      const status = checkbox.checked;

      const response = (await activatePage(pageId, status, csrfToken)) as unknown as Response;

      if (typeof response.success === 'string') {
        pushNotification(response.success);
      } else {
        pushErrorNotification(response.error || 'An error occurred');
        checkbox.checked = !status;
      }
    });
  });
};
