#!/bin/sh
#
# Entrypoint of the phpMyFAQ production image (Apache and FrankenPHP variants).
#
# 1. Prepares the writable content directories (they are usually volumes).
# 2. Writes the PHP settings taken from environment variables.
# 3. Installs phpMyFAQ headlessly when database and admin credentials are
#    given and no installation exists yet. Without them the web installer at
#    /setup/ is used instead.
# 4. Hands over to the web server.

set -eu

APP_DIR=/var/www/html
CONSOLE=/var/www/bin/console
# "cache" holds the compiled routes, container, Twig templates and plugin
# manifest in production mode; it is deliberately not a volume, so every new
# image starts with a fresh cache.
WRITABLE_DIRS="cache content/core/config content/core/data content/core/logs content/core/cache content/user/attachments content/user/images"

log() {
    printf '[phpmyfaq] %s\n' "$*"
}

cd "$APP_DIR"

# --- 1. writable directories -------------------------------------------------
for dir in $WRITABLE_DIRS; do
    mkdir -p "$dir"
done
if [ "$(id -u)" = "0" ]; then
    # Fresh volumes are root-owned; hand them to the PHP process user.
    # shellcheck disable=SC2086 # word splitting is intended
    chown -R www-data:www-data $WRITABLE_DIRS
fi

# --- 2. PHP settings from the environment -------------------------------------
{
    echo '; Generated by the phpMyFAQ container entrypoint from environment variables.'
    echo "date.timezone = ${PMF_TIMEZONE:-UTC}"
    echo "memory_limit = ${PMF_MEMORY_LIMIT:-512M}"
    echo "file_uploads = ${PMF_ENABLE_UPLOADS:-On}"
    echo "upload_max_filesize = ${PHP_UPLOAD_MAX_FILESIZE:-64M}"
    echo "post_max_size = ${PHP_POST_MAX_SIZE:-64M}"
    echo "log_errors = ${PHP_LOG_ERRORS:-On}"
    echo "error_reporting = ${PHP_ERROR_REPORTING:-E_ALL & ~E_DEPRECATED}"
    echo 'display_errors = Off'
    echo 'display_startup_errors = Off'
} > "$PHP_INI_DIR/conf.d/zz-phpmyfaq.ini"

# --- 3. optional headless installation ---------------------------------------
if [ -f content/core/config/database.php ]; then
    log "Existing installation found."
elif [ -n "${PMF_DB_HOST:-}" ] && [ -n "${PMF_ADMIN_PASSWORD:-}" ]; then
    db_type="${PMF_DB_TYPE:-mysqli}"
    case "$db_type" in
        pgsql) default_port=5432 ;;
        *) default_port=3306 ;;
    esac

    log "No installation found, installing with database ${db_type}://${PMF_DB_HOST}:${PMF_DB_PORT:-$default_port}/${PMF_DB_NAME:-phpmyfaq} ..."
    attempt=1
    max_attempts="${PMF_INSTALL_RETRIES:-12}"
    installed=0
    while [ "$attempt" -le "$max_attempts" ]; do
        if php "$CONSOLE" phpmyfaq:install --no-interaction \
            --db-type="$db_type" \
            --db-server="$PMF_DB_HOST" \
            --db-port="${PMF_DB_PORT:-$default_port}" \
            --db-name="${PMF_DB_NAME:-phpmyfaq}" \
            --db-user="${PMF_DB_USER:-phpmyfaq}" \
            --db-password="${PMF_DB_PASS:-}" \
            --admin-user="${PMF_ADMIN_USER:-admin}" \
            --admin-password="$PMF_ADMIN_PASSWORD" \
            --base-url="${PMF_BASE_URL:-http://localhost}"; then
            installed=1
            break
        fi
        log "Installation attempt ${attempt}/${max_attempts} failed (see above; a database that is still starting is the usual cause). Retrying in 5s ..."
        attempt=$((attempt + 1))
        sleep 5
    done

    if [ "$installed" = "1" ]; then
        log "Installation complete. Log in at ${PMF_BASE_URL:-http://localhost}/admin/ as ${PMF_ADMIN_USER:-admin}."
        [ "$(id -u)" = "0" ] && chown -R www-data:www-data content/core/config
    else
        log "WARNING: headless installation failed, the web installer stays available at /setup/."
    fi
else
    log "No installation found. Open /setup/ in the browser, or set PMF_DB_HOST, PMF_DB_USER, PMF_DB_PASS and PMF_ADMIN_PASSWORD to install headlessly."
fi

# --- 4. web server ------------------------------------------------------------
exec "$@"
